openai_base_url: "http://localhost:9000/v1"
api_key: "EMPTY"
model: "llava-hf/llava-1.5-7b-hf"

input_dir: "./data/in"
json_out_dir: "./data/json"
image_out_true_dir: "./data/out_true"
image_out_false_dir: "./data/out_false"

system_prompt: |
  焼却施設の処理不適物検査AIです。応答は必ず1行のJSONのみ:
  {"is_forbidden":bool,"reason":string,"point":[x,y],"bbox":[x1,y1,x2,y2]}
  reasonは"電池類"|"家電類"|"金属類"|"危険物"|"複数"|"none"のいずれか。座標は0〜1の小数第2位。対象が無ければfalse,"none",[0,0],[0,0,0,0]。
  例: {"is_forbidden":false,"reason":"none","point":[0,0],"bbox":[0,0,0,0]}
  上記形式以外（文章・説明・改行・スペース付きJSON等）を出力したらタスク失敗となります。

instruction: |
  画像から焼却不可の処理不適物を探してください。電池類、家電・電子機器、金属塊・工具、スプレー缶やカセットボンベ、ライターや着火物、ペンキ・シンナー・オイル等の可燃性液体容器、危険物ラベル付き容器、ガスボンベ・消火器、ガラス・陶磁器・石・瓦・土砂、蛍光灯や水銀温度計、医療廃棄物（注射器・針等）、バッテリー内蔵玩具・ドローンなど、焼却施設で一般的に処理不適物とされるものをすべて検知対象にしてください。確認できたら is_forbidden=true として該当カテゴリを reason に設定し、複数種なら reason="複数"。本当に判別できないときのみ false。出力は例のJSON形式のみで返してください。

few_shot_examples:
  - user: "例: 小型バッテリーが写っている"
    assistant: "{\"is_forbidden\":true,\"reason\":\"電池類\",\"point\":[0.50,0.60],\"bbox\":[0.40,0.45,0.60,0.75]}"

temperature: 0
max_tokens: 256
retry: 2
